/*
  QuoJS 1.0
  (c) 2011, 2012 Javi Jiménez Villar (@soyjavi)
  http://quojs.tapquo.com
*/
var Quo=function(){function a(e,d){e=e||g;e.__proto__=a.prototype;e.selector=d||"";return e}function h(e){if(e){var d=h.getDomainSelector(e);return a(d,e)}else return a()}var g=[];h.extend=function(e){Array.prototype.slice.call(arguments,1).forEach(function(d){for(key in d)e[key]=d[key]});return e};a.prototype=h.fn={};return h}();window.Quo=Quo;"$$"in window||(window.$$=Quo);(function(a){var h=Object.prototype,g=[];a.each=function(d,k){var f;if(typeof d.length=="number")for(f=0;f<d.length;f++){if(k.call(d[f],f,d[f])===false)break}else for(f in d)if(k.call(d[f],f,d[f])===false)break;return d};a.mix=function(){for(var d=d||{},k=0,f=arguments.length;k<f;k++){var l=arguments[k],j;for(j in l)if(a.isOwnProperty(l,j))d[j]=l[j]}return d};a.toType=function(d){return h.toString.call(d).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()};a.isOwnProperty=function(d,k){return h.hasOwnProperty.call(d,
k)};a.getDomainSelector=function(d){var k=null,f=[1,9,11],l=a.toType(d);if(l==="string")k=queryDOM(document,d);else if(l==="array")k=e(d);else if(f.indexOf(d.nodeType)>=0||d===window)k=[d];else console.error("ERROR: The selector is invalid");return k};a.fn.forEach=g.forEach;a.fn.indexOf=g.indexOf;a.fn.pluck=function(d){return this.map(function(){return this[d]})};var e=function(d){return d.filter(function(k){return k!==undefined&&k!==null})}})(Quo);(function(a){a.fn.attr=function(h,g){return a.toType(h)==="string"&&g===undefined?this[0].getAttribute(h):this.each(function(){this.setAttribute(h,g)})};a.fn.data=function(h,g){return this.attr("data-"+h,g)};a.fn.val=function(h){return h?this.each(function(){this.value=h}):this.length>0?this[0].value:null};a.fn.height=function(){};a.fn.width=function(){};a.fn.offset=function(){var h=this[0].getBoundingClientRect();return{left:h.left+window.pageXOffset,top:h.top+window.pageYOffset,width:h.width,height:h.height}};
a.fn.remove=function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})}})(Quo);(function(a){var h=/WebKit\/([\d.]+)/,g={android:/(Android)\s+([\d.]+)/,ipad:/(iPad).*OS\s([\d_]+)/,iphone:/(iPhone\sOS)\s([\d_]+)/,blackberry:/(BlackBerry).*Version\/([\d.]+)/,webos:/(webOS|hpwOS)[\s\/]([\d.]+)/},e=null;a.isMobile=function(){e=e||d();return e.isMobile};a.environment=function(){return e=e||d()};a.isOnline=isOnline=function(){return navigator.onLine?true:false};var d=function(){var k=navigator.userAgent,f={},l=k.match(h);f.browser=l?l[0]:k;var j;for(os in g)if(l=k.match(g[os])){j=
{name:os==="iphone"||os==="ipad"?"ios":os,version:l[2]};break}f.os=j;f.isMobile=f.os?true:false;return f}})(Quo);(function(a){a.fn.text=function(h){return!h?this[0].textContent:this.each(function(){this.textContent=h})};a.fn.html=function(h){return!h?this[0].innerHTML:this.each(function(){this.innerHTML=h})};a.fn.append=function(h){return this.each(function(){if(a.toType(h)==="string"){var g=document.createElement();g.innerHTML=h;this.appendChild(g.firstChild)}else this.parentNode.insertBefore(h)})};a.fn.prepend=function(h){return this.each(function(){if(a.toType(h)==="string")this.innerHTML=h+this.innerHTML;
else{var g=this.parentNode;g.insertBefore(h,g.firstChild)}})};a.fn.empty=function(){return this.each(function(){this.innerHTML=null})}})(Quo);(function(a){a.query=queryDOM=function(g,e){var d=document.querySelectorAll(e);return d=Array.prototype.slice.call(d)};a.fn.parent=function(g){var e=this.pluck("parentNode");return h(e,g)};a.fn.siblings=function(g){var e=this.map(function(d,k){return Array.prototype.slice.call(k.parentNode.children).filter(function(f){return f!==k})});return h(e,g)};a.fn.children=function(g){var e=this.map(function(){return Array.prototype.slice.call(this.children)});return h(e,g)};a.fn.get=function(g){return g===
undefined?this:this[g]};a.fn.first=function(){return a(this[0])};a.fn.last=function(){return a(this[this.length-1])};a.fn.closest=function(g,e){var d=this[0],k=a(g);for(k.length||(d=null);d&&k.indexOf(d)<0;)d=d!==e&&d!==document&&d.parentNode;return a(d)};a.fn.each=function(g){this.forEach(function(e,d){g.call(e,d,e)});return this};var h=function(g,e){return e===undefined?a(g):a(g).filter(e)}})(Quo);(function(a){function h(g,e){return e.split(/\s+/g).indexOf(g)>=0?true:false}a.fn.addClass=function(g){return this.each(function(){h(g,this.className)||(this.className+=" "+g)})};a.fn.removeClass=function(g){var e=RegExp("(^|\\s+)"+g+"(\\s+|$)");return this.each(function(){if(h(g,this.className))this.className=this.className.replace(e," ")})};a.fn.toggleClass=function(g){var e=RegExp("(^|\\s+)"+g+"(\\s+|$)");return this.each(function(){if(h(g,this.className))this.className=this.className.replace(e,
"");else this.className+=" "+g})};a.fn.hasClass=function(g){return h(g,this[0].className)};a.fn.style=function(g,e){return!e?this[0].style[g]:this.each(function(){this.style[g]=e})}})(Quo);(function(a){function h(j,b){if(b.contentType)b.headers["Content-Type"]=b.contentType;if(b.dataType)b.headers.Accept=k[b.dataType];for(header in b.headers)j.setRequestHeader(header,b.headers[header])}function g(j,b){j.onreadystatechange={};j.abort();b.error.call(b.context,"QuoJS \u00bb $$.ajax : timeout exceeded",j,b)}function e(j,b){var c=j.responseText;if(b.dataType===d.MIME)try{c=JSON.parse(c)}catch(i){c=i;b.error.call(b.context,"Parse Error",j,b)}return c}var d={TYPE:"GET",MIME:"json"},k={script:"text/javascript, application/javascript",
json:"application/json",xml:"application/xml, text/xml",html:"text/html",text:"text/plain"},f=0;a.ajaxSettings={type:d.TYPE,async:true,success:{},error:{},context:null,dataType:d.MIME,headers:{},xhr:function(){return new window.XMLHttpRequest},crossDomain:false,timeout:0};a.ajax=function(j){var b=a.mix(a.ajaxSettings,j);if(/=\?/.test(b.url))return a.jsonp(b);var c=b.xhr();c.onreadystatechange=function(){if(c.readyState===4){clearTimeout(i);if(c.status===200){if(b.async){var m=e(c,b);b.success.call(b.context,
m,c)}}else b.error.call(b.context,"QuoJS \u00bb $$.ajax",c,b)}};c.open(b.type,b.url,b.async);h(c,b);if(b.timeout>0)var i=setTimeout(function(){g(c,b)},b.timeout);c.send(b.data);return b.async?c:e(c,b)};a.jsonp=function(j){var b="jsonp"+ ++f,c=document.createElement("script"),i={abort:function(){a(c).remove();if(b in window)window[b]={}}},m;window[b]=function(o){clearTimeout(m);a(c).remove();delete window[b];j.success.call(j.context,o,i)};c.src=j.url.replace(/=\?/,"="+b);a("head").append(c);if(j.timeout>
0)m=setTimeout(function(){g(i,j)},j.timeout);return i};a.get=function(j,b,c,i){j+=l(b);return a.ajax({url:j,success:c,dataType:i})};a.post=function(j,b,c,i){return a.ajax({type:"POST",url:j,data:b,success:c,dataType:i,contentType:"application/x-www-form-urlencoded"})};a.json=function(j,b,c){j+=l(b);console.error("json ",j);return a.ajax({url:j,success:c,dataType:d.MIME})};var l=function(j){var b="?",c;for(c in j)if(j.hasOwnProperty(c)){if(b!=="?")b+="&";b+=c+"="+j[c]}return b==="?"?"":b}})(Quo);(function(a){var h={touch:"touchstart",tap:"tap"},g=/complete|loaded|interactive/;["touch","tap"].forEach(function(e){a.fn[e]=function(d){a(document.body).delegate(this.selector,h[e],d);return this}});a.fn.on=function(e,d,k){return d===undefined||a.toType(d)==="function"?this.bind(e,d):this.delegate(d,e,k)};a.fn.off=function(e,d,k){return d===undefined||a.toType(d)==="function"?this.unbind(e,d):this.undelegate(d,e,k)};a.fn.ready=function(e){g.test(document.readyState)?e(a):document.addEventListener("DOMContentLoaded",
function(){e(a)},false);return this}})(Quo);(function(a){function h(c,i,m,o,n){i=a.isMobile()?i:b[i];var p=c._id||(c._id=f++);p=l[p]||(l[p]=[]);n=n&&n(m,i);i={event:i,callback:m,selector:o,proxy:e(n,m,c),delegate:n,index:p.length};p.push(i);c.addEventListener(i.event,i.proxy,false)}function g(c,i,m,o){i=a.isMobile()?i:b[i];var n=c._id||(c._id=f++);d(n,i,m,o).forEach(function(p){delete l[n][p.index];c.removeEventListener(p.event,p.proxy,false)})}function e(c,i,m){i=c||i;return function(o){var n=i.apply(m,[o].concat(o.data));n===false&&o.preventDefault();
return n}}function d(c,i,m,o){return(l[c]||[]).filter(function(n){return n&&(!i||n.event==i)&&(!m||n.fn==m)&&(!o||n.selector==o)})}function k(c){var i=a.extend({originalEvent:c},c);a.each(j,function(m,o){i[m]=function(){this[o]=function(){return true};return c[m].apply(c,arguments)};i[o]=function(){return false}});return i}var f=1,l={},j={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"},b={touchstart:"mousedown",touchmove:"mousemove",
touchend:"mouseup",tap:"click",doubletap:"dblclick",orientation_change:"resize"};a.Event=function(c){var i=document.createEvent("Events");i.initEvent(c,true,true,null,null,null,null,null,null,null,null,null,null,null,null);return i};a.fn.bind=function(c,i){return this.each(function(){h(this,c,i)})};a.fn.unbind=function(c,i){return this.each(function(){g(this,c,i)})};a.fn.trigger=function(c){a.isMobile()||console.log("Event "+c+" captured.");if(a.toType(c)==="string")c=a.Event(c);return this.each(function(){this.dispatchEvent(c)})};
a.fn.delegate=function(c,i,m){return this.each(function(o,n){h(n,i,m,c,function(p){return function(r){var q=a(r.target).closest(c,n).get(0);if(q){var s=a.extend(k(r),{currentTarget:q,liveFired:n});return p.apply(q,[s].concat([].slice.call(arguments,1)))}}})})};a.fn.undelegate=function(c,i,m){return this.each(function(){g(this,i,m,c)})}})(Quo);(function(a){function h(b){var c=Date.now(),i=c-(f.last||c);b=a.isMobile()?b.touches[0]:b;l&&clearTimeout(l);f={el:a("tagName"in b.target?b.target:b.target.parentNode),x1:b.pageX,y1:b.pageY,isDoubleTap:i>0&&i<=250?true:false,last:c};setTimeout(k,j)}function g(b){b=a.isMobile()?b.touches[0]:b;f.x2=b.pageX;f.y2=b.pageY}function e(){if(f.isDoubleTap){f.el.trigger("doubleTap");f={}}else if(f.x2>0||f.y2>0){(Math.abs(f.x1-f.x2)>30||Math.abs(f.y1-f.y2)>30)&&f.el.trigger("swipe")&&f.el.trigger("swipe"+(Math.abs(f.x1-
f.x2)>=Math.abs(f.y1-f.y2)?f.x1-f.x2>0?"Left":"Right":f.y1-f.y2>0?"Up":"Down"));f.x1=f.x2=f.y1=f.y2=f.last=0;f={}}else l=setTimeout(function(){l=null;f={}},250)}function d(){f={};clearTimeout(l)}function k(){if(f.last&&Date.now()-f.last>=j){f.el.trigger("longTap");f={}}}var f={},l,j=750;["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","longTap"].forEach(function(b){a.fn[b]=function(c){return this.on(b,c)}});a(document).ready(function(){var b=a(document.body);b.bind("touchstart",
h);b.bind("touchmove",g);b.bind("touchend",e);b.bind("touchcancel",d)})})(Quo);
