/*!
 * QuoJS 1.0.3 ~ Copyright (c) 2011, 2012 Javi Jiménez Villar (@soyjavi)
 * http://quojs.tapquo.com
 * Released under MIT license, https://raw.github.com/soyjavi/QuoJS/master/LICENSE.txt
 */

var Quo=function(){function a(f,b){f=f||j;f.__proto__=a.prototype;f.selector=b||"";return f}function i(f){if(f){var b=i.getDomainSelector(f);return a(b,f)}else return a()}var j=[];i.extend=function(f){Array.prototype.slice.call(arguments,1).forEach(function(b){for(key in b)f[key]=b[key]});return f};a.prototype=i.fn={};return i}();window.Quo=Quo;"$$"in window||(window.$$=Quo);(function(a){function i(b){return b.filter(function(g){return g!==undefined&&g!==null})}var j=Object.prototype,f=[];a.toType=function(b){return j.toString.call(b).match(/\s([a-z|A-Z]+)/)[1].toLowerCase()};a.isOwnProperty=function(b,g){return j.hasOwnProperty.call(b,g)};a.getDomainSelector=function(b){var g=null,d=[1,9,11],l=a.toType(b);if(l==="array")g=i(b);else if(l==="string")g=a.query(document,b);else if(d.indexOf(b.nodeType)>=0||b===window)g=[b];return g};a.map=function(b,g){var d=[],l;if(a.toType(b)===
"array")for(l=0;l<b.length;l++){var k=g(b[l],l);k!=null&&d.push(k)}else for(l in b){k=g(b[l],l);k!=null&&d.push(k)}return d.length>0?[].concat.apply([],d):d};a.each=function(b,g){var d;if(a.toType(b)==="array")for(d=0;d<b.length;d++){if(g.call(b[d],d,b[d])===false)break}else for(d in b)if(g.call(b[d],d,b[d])===false)break;return b};a.mix=function(){for(var b={},g=0,d=arguments.length;g<d;g++){var l=arguments[g],k;for(k in l)if(a.isOwnProperty(l,k)&&l[k]!==undefined)b[k]=l[k]}return b};a.fn.forEach=
f.forEach;a.fn.indexOf=f.indexOf;a.fn.map=function(b){return a.map(this,function(g,d){return b.call(g,d,g)})};a.fn.instance=function(b){return this.map(function(){return this[b]})};a.fn.filter=function(b){return a([].filter.call(this,function(g){return g.parentNode&&a.query(g.parentNode,b).indexOf(g)>=0}))}})(Quo);(function(a){a.fn.attr=function(i,j){return a.toType(i)==="string"&&j===undefined?this[0].getAttribute(i):this.each(function(){this.setAttribute(i,j)})};a.fn.data=function(i,j){return this.attr("data-"+i,j)};a.fn.val=function(i){return a.toType(i)==="string"?this.each(function(){this.value=i}):this.length>0?this[0].value:null};a.fn.show=function(){return this.style("display","block")};a.fn.hide=function(){return this.style("display","none")};a.fn.height=function(){return this.offset().height};a.fn.width=
function(){return this.offset().width};a.fn.offset=function(){var i=this[0].getBoundingClientRect();return{left:i.left+window.pageXOffset,top:i.top+window.pageYOffset,width:i.width,height:i.height}};a.fn.remove=function(){return this.each(function(){this.parentNode!=null&&this.parentNode.removeChild(this)})}})(Quo);(function(a){var i=/WebKit\/([\d.]+)/,j={android:/(Android)\s+([\d.]+)/,ipad:/(iPad).*OS\s([\d_]+)/,iphone:/(iPhone\sOS)\s([\d_]+)/,blackberry:/(BlackBerry).*Version\/([\d.]+)/,webos:/(webOS|hpwOS)[\s\/]([\d.]+)/},f=null;a.isMobile=function(){f=f||b();return f.isMobile};a.environment=function(){return f=f||b()};a.isOnline=function(){return navigator.onLine};var b=function(){var g=navigator.userAgent,d={},l=g.match(i);d.browser=l?l[0]:g;var k;for(os in j)if(l=g.match(j[os])){k={name:os==="iphone"||
os==="ipad"?"ios":os,version:l[2].replace("_",".")};break}d.os=k;d.isMobile=d.os?true:false;return d}})(Quo);(function(a){a.fn.text=function(i){return!i?this[0].textContent:this.each(function(){this.textContent=i})};a.fn.html=function(i){return a.toType("value")==="string"?this.each(function(){this.innerHTML=i}):this[0].innerHTML};a.fn.append=function(i){return this.each(function(){if(a.toType(i)==="string"){if(i){var j=document.createElement();j.innerHTML=i;this.appendChild(j.firstChild)}}else this.insertBefore(i)})};a.fn.prepend=function(i){return this.each(function(){if(a.toType(i)==="string")this.innerHTML=
i+this.innerHTML;else{var j=this.parentNode;j.insertBefore(i,j.firstChild)}})};a.fn.empty=function(){return this.each(function(){this.innerHTML=null})}})(Quo);(function(a){a.query=function(f,b){var g=document.querySelectorAll(b);return g=Array.prototype.slice.call(g)};a.fn.parent=function(f){var b=f?i(this):this.instance("parentNode");return j(b,f)};a.fn.siblings=function(f){var b=this.map(function(g,d){return Array.prototype.slice.call(d.parentNode.children).filter(function(l){return l!==d})});return j(b,f)};a.fn.children=function(f){var b=this.map(function(){return Array.prototype.slice.call(this.children)});return j(b,f)};a.fn.get=function(f){return f===
undefined?this:this[f]};a.fn.first=function(){return a(this[0])};a.fn.last=function(){return a(this[this.length-1])};a.fn.closest=function(f,b){var g=this[0],d=a(f);for(d.length||(g=null);g&&d.indexOf(g)<0;)g=g!==b&&g!==document&&g.parentNode;return a(g)};a.fn.each=function(f){this.forEach(function(b,g){f.call(b,g,b)});return this};var i=function(f){for(var b=[];f.length>0;)f=a.map(f,function(g){if((g=g.parentNode)&&g!==document&&b.indexOf(g)<0){b.push(g);return g}});return b},j=function(f,b){return b===
undefined?a(f):a(f).filter(b)}})(Quo);(function(a){function i(j,f){return f.split(/\s+/g).indexOf(j)>=0}a.fn.addClass=function(j){return this.each(function(){i(j,this.className)||(this.className+=" "+j)})};a.fn.removeClass=function(j){return this.each(function(){if(i(j,this.className))this.className=this.className.replace(j," ").replace(/\s+/gi," ")})};a.fn.toggleClass=function(j){return this.each(function(){if(i(j,this.className))this.className=this.className.replace(j," ");else this.className+=" "+j})};a.fn.hasClass=function(j){return i(j,
this[0].className)};a.fn.style=function(j,f){return!f?this[0].style[j]||document.defaultView.getComputedStyle(this[0],"")[j]:this.each(function(){this.style[j]=f})}})(Quo);(function(a){function i(k,c){if(c.contentType)c.headers["Content-Type"]=c.contentType;if(c.dataType)c.headers.Accept=g[c.dataType];for(header in c.headers)k.setRequestHeader(header,c.headers[header])}function j(k,c){k.onreadystatechange={};k.abort();c.error.call(c.context,"QuoJS \u00bb $$.ajax : timeout exceeded",k,c)}function f(k,c){var e=k.responseText;if(e)if(c.dataType===b.MIME)try{e=JSON.parse(e)}catch(h){e=h;c.error.call(c.context,"Parse Error",k,c)}else if(c.dataType==="xml")e=k.responseXML;
return e}var b={TYPE:"GET",MIME:"json"},g={script:"text/javascript, application/javascript",json:"application/json",xml:"application/xml, text/xml",html:"text/html",text:"text/plain"},d=0;a.ajaxSettings={type:b.TYPE,async:true,success:{},error:{},context:null,dataType:b.MIME,headers:{},xhr:function(){return new window.XMLHttpRequest},crossDomain:false,timeout:0};a.ajax=function(k){var c=a.mix(a.ajaxSettings,k);if(/=\?/.test(c.url))return a.jsonp(c);var e=c.xhr();e.onreadystatechange=function(){if(e.readyState===
4){clearTimeout(h);if(e.status===200||e.status===0){if(c.async){var m=f(e,c);c.success.call(c.context,m,e)}}else c.error.call(c.context,"QuoJS \u00bb $$.ajax",e,c)}};e.open(c.type,c.url,c.async);i(e,c);if(c.timeout>0)var h=setTimeout(function(){j(e,c)},c.timeout);e.send(c.data);return c.async?e:f(e,c)};a.jsonp=function(k){var c="jsonp"+ ++d,e=document.createElement("script"),h={abort:function(){a(e).remove();if(c in window)window[c]={}}},m;window[c]=function(o){clearTimeout(m);a(e).remove();delete window[c];
k.success.call(k.context,o,h)};e.src=k.url.replace(/=\?/,"="+c);a("head").append(e);if(k.timeout>0)m=setTimeout(function(){j(h,k)},k.timeout);return h};a.get=function(k,c,e,h){k+=l(c);return a.ajax({url:k,success:e,dataType:h})};a.post=function(k,c,e,h){return a.ajax({type:"POST",url:k,data:c,success:e,dataType:h,contentType:"application/x-www-form-urlencoded"})};a.json=function(k,c,e){k+=l(c);return a.ajax({url:k,success:e,dataType:b.MIME})};var l=function(k){var c="?",e;for(e in k)if(k.hasOwnProperty(e)){if(c!==
"?")c+="&";c+=e+"="+k[e]}return c==="?"?"":c}})(Quo);(function(a){var i={touch:"touchstart",tap:"tap"},j=/complete|loaded|interactive/;["touch","tap"].forEach(function(f){a.fn[f]=function(b){a(document.body).delegate(this.selector,i[f],b);return this}});a.fn.on=function(f,b,g){return b===undefined||a.toType(b)==="function"?this.bind(f,b):this.delegate(b,f,g)};a.fn.off=function(f,b,g){return b===undefined||a.toType(b)==="function"?this.unbind(f,b):this.undelegate(b,f,g)};a.fn.ready=function(f){j.test(document.readyState)?f(a):document.addEventListener("DOMContentLoaded",
function(){f(a)},false);return this}})(Quo);(function(a){function i(e,h,m,o,n){h=(a.isMobile()?h:c[h])||h;var p=e._id||(e._id=d++);p=l[p]||(l[p]=[]);n=n&&n(m,h);h={event:h,callback:m,selector:o,proxy:f(n,m,e),delegate:n,index:p.length};p.push(h);e.addEventListener(h.event,h.proxy,false)}function j(e,h,m,o){h=(a.isMobile()?h:c[h])||h;var n=e._id||(e._id=d++);b(n,h,m,o).forEach(function(p){delete l[n][p.index];e.removeEventListener(p.event,p.proxy,false)})}function f(e,h,m){h=e||h;return function(o){var n=h.apply(m,[o].concat(o.data));n===false&&
o.preventDefault();return n}}function b(e,h,m,o){return(l[e]||[]).filter(function(n){return n&&(!h||n.event==h)&&(!m||n.fn==m)&&(!o||n.selector==o)})}function g(e){var h=a.extend({originalEvent:e},e);a.each(k,function(m,o){h[m]=function(){this[o]=function(){return true};return e[m].apply(e,arguments)};h[o]=function(){return false}});return h}var d=1,l={},k={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",stopPropagation:"isPropagationStopped"},c={touchstart:"mousedown",
touchmove:"mousemove",touchend:"mouseup",tap:"click",doubletap:"dblclick",orientationchange:"resize"};a.Event=function(e){var h=document.createEvent("Events");h.initEvent(e,true,true,null,null,null,null,null,null,null,null,null,null,null,null);return h};a.fn.bind=function(e,h){return this.each(function(){i(this,e,h)})};a.fn.unbind=function(e,h){return this.each(function(){j(this,e,h)})};a.fn.delegate=function(e,h,m){return this.each(function(o,n){i(n,h,m,e,function(p){return function(r){var q=a(r.target).closest(e,
n).get(0);if(q){var s=a.extend(g(r),{currentTarget:q,liveFired:n});return p.apply(q,[s].concat([].slice.call(arguments,1)))}}})})};a.fn.undelegate=function(e,h,m){return this.each(function(){j(this,h,m,e)})};a.fn.trigger=function(e){if(a.toType(e)==="string")e=a.Event(e);return this.each(function(){this.dispatchEvent(e)})}})(Quo);(function(a){function i(c){var e=Date.now(),h=e-(d.last||e);c=a.isMobile()?c.touches[0]:c;l&&clearTimeout(l);d={el:a("tagName"in c.target?c.target:c.target.parentNode),x1:c.pageX,y1:c.pageY,isDoubleTap:h>0&&h<=250?true:false,last:e};setTimeout(g,k)}function j(c){c=a.isMobile()?c.touches[0]:c;d.x2=c.pageX;d.y2=c.pageY}function f(){if(d.isDoubleTap){d.el.trigger("doubleTap");d={}}else if(d.x2>0||d.y2>0){(Math.abs(d.x1-d.x2)>30||Math.abs(d.y1-d.y2)>30)&&d.el.trigger("swipe")&&d.el.trigger("swipe"+(Math.abs(d.x1-
d.x2)>=Math.abs(d.y1-d.y2)?d.x1-d.x2>0?"Left":"Right":d.y1-d.y2>0?"Up":"Down"));d.x1=d.x2=d.y1=d.y2=d.last=0;d={}}else{d.el!==undefined&&d.el.trigger("tap");l=setTimeout(function(){l=null;d={}},250)}}function b(){d={};clearTimeout(l)}function g(){if(d.last&&Date.now()-d.last>=k){d.el.trigger("longTap");d={}}}var d={},l,k=750;["swipe","swipeLeft","swipeRight","swipeUp","swipeDown","doubleTap","longTap"].forEach(function(c){a.fn[c]=function(e){return this.on(c,e)}});a(document).ready(function(){var c=
a(document.body);c.bind("touchstart",i);c.bind("touchmove",j);c.bind("touchend",f);c.bind("touchcancel",b)})})(Quo);
